-- AlterEnum
ALTER TYPE "EchoStatus" ADD VALUE 'DEACTIVATE';

-- AlterEnum
ALTER TYPE "EventStatus" ADD VALUE 'DEACTIVATE';

-- AlterTable
ALTER TABLE "userMembership" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "oldPrice" SET DATA TYPE DOUBLE PRECISION;
