export const domains = [
  "mydjlife.me",
  "myinfluencerlife.me",
  "mystudentlife.me",
  "myrestaurantlife.me",
  "mybusinesslife.me",
  "mycheflife.me",
  "mymusiclife.me",
  "mypizzalife.me",
  "mystorelife.me",
  "mybartendinglife.me",
  "myfreelancerlife.me",
  "myservicelife.me",
  "mytemplife.me",
  "mycookinglife.me",
  "mycpalife.me",
  "myentertainmentlife.me",
  "mynightlife.me",
  "myailife.me",
  "myclublife.me",
  "mymedialife.me",
  "mystylistlife.me",
  "mydevlife.me",
  "mylatinlife.me",
  "mymakerlife.me",
  "mysaloonLife.me",
  "mybarberlife.me",
  "mygymlife.me",
  "mynitelife.me",
  "mysalonlife.me",
  "myworldlife.me",
  "mybarlife.me",
  "myeventlife.me",
];

export const packageData = [
  { key: "bronze", value: "bronze" },
  { key: "silver", value: "silver" },
  { key: "gold", value: "gold" },
  { key: "platinum", value: "platinum" },
];

export const frequencyData = [
  { key: "monthly", value: "monthly" },
  { key: "yearly", value: "yearly" },
];

export const planData = [
  { key: "SPARK_BRONZE_MONTHLY", value: "SPARK_BRONZE_MONTHLY" },
  { key: "SPARK_BRONZE_YEARLY", value: "SPARK_BRONZE_YEARLY" },
  { key: "SPARK_SILVER_MONTHLY", value: "SPARK_SILVER_MONTHLY" },
  { key: "SPARK_SILVER_YEARLY", value: "SPARK_SILVER_YEARLY" },
  { key: "SPARK_GOLD_MONTHLY", value: "SPARK_GOLD_MONTHLY" },
  { key: "SPARK_GOLD_YEARLY", value: "SPARK_GOLD_YEARLY" },
  { key: "PULSE_BRONZE_MONTHLY", value: "PULSE_BRONZE_MONTHLY" },
  { key: "PULSE_BRONZE_YEARLY", value: "PULSE_BRONZE_YEARLY" },
  { key: "PULSE_SILVER_MONTHLY", value: "PULSE_SILVER_MONTHLY" },
  { key: "PULSE_SILVER_YEARLY", value: "PULSE_SILVER_YEARLY" },
  { key: "PULSE_GOLD_MONTHLY", value: "PULSE_GOLD_MONTHLY" },
  { key: "PULSE_GOLD_YEARLY", value: "PULSE_GOLD_YEARLY" },
  { key: "POWER_SILVER_MONTHLY", value: "POWER_SILVER_MONTHLY" },
  { key: "POWER_SILVER_YEARLY", value: "POWER_SILVER_YEARLY" },
  { key: "POWER_GOLD_MONTHLY", value: "POWER_GOLD_MONTHLY" },
  { key: "POWER_GOLD_YEARLY", value: "POWER_GOLD_YEARLY" },
];
