const response = {
  HOME_ROUTE_MESSAGE: "Home route",
  UNAUTHORIZE_ERROR_MESSAGE: "Unauthorize user!",
  ROUTE_NOT_FOUND_MESSAGE: "Route not found!",
  USER_ALREADY_EXIST_MESSAGE: "User already exist!",
  REGISTRATION_SUCCESS_MESSAGE: "Successful, redirect to payment",
  EMAIL_VERIFICATION_CODE_RESPONSE: "Verify Your Email for My Brand Life",
  NAME_RESPONSE: "The My Brand Life Team",
  OUTRO_RESPONSE: "©2025 My Brand Life. All rights reserved.",
  USE_VERIFICATION_CODE_TO_VERIFY_EMAIL_RESPONSE:
    "Welcome to My Brand Life! Please use the following confirmation code to verify your email address.",
  SINGNATURE_RESPONSE: "Kind regards",
  IGNORE_EMAIL_RESPONSE:
    "If you have not signed up for this account, you can ignore this email.",
  DATA_NOT_FOUND_MESSAGE: "Data not found!",
  DELETE_SUCCESS_MESSAGE: "Delete successful",
  PASSWORD_NOT_MATCH_MESSAGE: "Password incorrect!",
  LOGIN_SUCCESS_MESSAGE: "Login successful",
  QUERY_SUCCESSFUL_MESSAGE: "Query successful",
  UPDATE_SUCCESSFUL_MESSAGE: "Update successful",
  ONBOARDING_SUCCESSFUL_MESSAGE: "Onboard submit successful",
  INCORRECT_REFERRAL_CODE_MESSAGE: "Incorrect referral code!",
  VALID_REFERRAL_CODE_MESSAGE: "Referral code Valid",
  TOKEN_EXPIRED_MESSAGE: "This code expired. Request a new one.",
  VERIFY_SUCCESSFUL_MESSAGE: "Email verified! Redirecting…",
  OTP_INCORRECT_MESSAGE: "That code doesn't look right. Try again.",
  USER_UNVERIFYED_MESSAGE: "User not activated!",
  OTP_CODE_SEND_MESSAGE: "OTP code send",
  MESSAGE_SEND_SUCCESSFUL_MESSAGE: "Message send successful",
  REQUEST_SUBMIT_SUCCESSFUL_MESSAGE: "Request submit successful",
  LANDER_ALREADY_EXIST_MESSAGE: "Landername alreadt exist!",
  INVALID_TOKEN_MESSAGE: "Invalid token",
  LOGOUT_SUCCESSFUL_MESSAGE: "Logut Successful",
  ONBOARD_ALREADY_CREATED_MESSAGE: "Onboard already created!",
  INVALID_PLAN_MESSAGE: "Invalid plan!",
  REFFERAL_ALREADY_EXIST: "Referral code already exist!",
  CORS_ERROR_MESSAGE: "Cors error origin not allow!",
  INVALID_SECURE_KEY_MESSAGE: "Invalid secure Key!",
  USER_VERIFY_SUCCESSFUL_MESSAGE: "Verify successful",
  FORM_SUBMITION_SUCCESSFUL_MESSAGE: "Submit successful, redireting",
  BOOKING_SUBMIT_SUCCESSFUL: "Booking submit successful",
  ACCOUNT_IS_DEACTIVATE_MESSAGE: "Deactivate account successful",
  CONNECTION_REDIRECT_MESSAGE: "Connection redirect",
  USER_STRIPE_CONNECTION_FAILED: "Stripe connection failed!",
};

module.exports = response;
